### PR TITLE
Make one timer rather than a timer each iteration.

### PR DESCRIPTION
**Pull request by rstorr**
Rather than creating a new timer for each iteration, one timer should be defined and reset after each iteration. When using time.After() it's valuable to know that ["The underlying Timer is not recovered by the garbage collector until the timer fires. If efficiency is a concern, use NewTimer instead and call Timer.Stop if the timer is no longer needed."](https://golang.org/src/time/sleep.go?s=4332:4733#L143)

This issue was found using the CodeLingo Tenet [ticker-in-for-select](https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/go/ticker-in-for-select/codelingo.yaml) which I have added to the codelingo.yaml at the root of the repo.

### CODE REVIEW

**Comment by rstorr** [comment]
travis CI failed, only on go 1.11. Failure looks unrelated to my PR. Looks like I don't have permissions to rerun travis.

**Comment by rfjakob** [comment]
Hmm, looks like we now have

```
for {
    select {
    case sb := <-sr.input:
        timer.Stop()
        [...]
        continue
    }
}
```
which means the time is stopped for the next iteration and timeout is broken, right?

**Comment by rfjakob** [comment]
-serialize_reads did not have a test, unfortunately, but now it does: https://github.com/rfjakob/gocryptfs/commit/7eba4f0788e95e3ac47856662ea4ebd986d358cd
Please rebase to master and test.

I see it hang here:
```
goroutine 34 [chan receive]:
github.com/rfjakob/gocryptfs/internal/serialize_reads.(*serializerState).wait(...)
	github.com/rfjakob/gocryptfs/internal/serialize_reads/sr.go:51
github.com/rfjakob/gocryptfs/internal/serialize_reads.Wait(...)
	github.com/rfjakob/gocryptfs/internal/serialize_reads/sr.go:23
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*File).Read(0xc0000de150, 0xc000104000, 0x1000, 0x1000, 0x0, 0x0, 0x0, 0xc000000000)
	github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:244 +0x506
github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).Read(0xc00008a9c0, 0x6e0e40, 0xc0000de150, 0xc000104000, 0x1000, 0x1000, 0x0, 0xc00011e100, 0xc00011e0e0, 0xc000164e70, ...)
	github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:748 +0x65
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Read(0xc00008ad20, 0xc00011c0c0, 0xc0001423d8, 0xc000104000, 0x1000, 0x1000, 0xc000164f78, 0x52b1b6, 0xc0000e0318)
	github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:454 +0x148
github.com/hanwen/go-fuse/fuse.doRead(0xc0000e0280, 0xc000142240)
	github.com/hanwen/go-fuse/fuse/opcode.go:349 +0x9f
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc0000e0280, 0xc000142240, 0xc000000000)
	github.com/hanwen/go-fuse/fuse/server.go:469 +0x277
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc0000e0280, 0xc00000e001)
	github.com/hanwen/go-fuse/fuse/server.go:436 +0x17d
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	github.com/hanwen/go-fuse/fuse/server.go:303 +0x39e
```

**Comment by rstorr** [comment]
@rfjakob thanks for the review and the test. tests are now passing :)

**Comment by rfjakob** [comment]
I benchmarked this: Before:

    10485760 bytes (10 MB, 10 MiB) copied, 0.0921577 s, 114 MB/s

After:

    10485760 bytes (10 MB, 10 MiB) copied, 0.0916671 s, 114 MB/s

As there no discernible change in performance, I'll have to reject this due to the extra complexity it introduces, sorry.

**Pull request closed without merging**
