### PR TITLE
nametransform: Return error if decrypted name is '.' or '..'

### PR DESCRIPTION
**Pull request by slackner**
Proposed fix for issue #163.

### CODE REVIEW

**Comment by rfjakob** [comment]
I would merge this right away if Travis testing was working. I hope to get more info out of https://github.com/travis-ci/travis-ci/issues/8790

**Comment by rfjakob** [comment]
I got a reply and this seems to be a false positive in their abuse detection system. The blocked requests are shown in a hidden tab: https://travis-ci.org/rfjakob/gocryptfs/requests .

As a workaround they suggest that you sign into https://travis-ci.org/ once (see below). Is this acceptable for you?

> I've been looking into these rejected requests and I see that the fds-team organization nor any of its members have been never logged into Travis CI and this is why we are currently blocking these requests that come from fds-team's fork of your rfjakob/gocryptfs repository. Sorry for the inconvenience.
> 
> We are looking into fixing this false positive in our abuse detection system, as we don't feel that an organization or account should have to create a Travis account when working with another project that is using Travis CI.
> 
> To sort this out in the meantime, do you know who manages this organization and do you think one of their members could try to log into Travis CI at least once at https://travis-ci.org/ and try closing and reopen one of the rejected Pull Requests?

**Comment by slackner** [comment]
> As a workaround they suggest that you sign into https://travis-ci.org/ once (see below). Is this acceptable for you?

I just did that, hopefully it will work now. Nevertheless, I find it a bit weird that all contributors need Travis accounts?! I would still consider that a bug in their system.

**Comment by rfjakob** [comment]
I have never seen that problem, maybe only happens when the repo is owned by an organization? Anyway, seems to work now, thanks!

**Pull request merged**
