### PR TITLE
Symlink race fixes

### PR DESCRIPTION
**Pull request by slackner**
Several fixes for the `symlink_race` branch.

### CODE REVIEW

**Comment by slackner** [comment]
Actually, before you merge it, I have some more changes. I will update this branch in a few minutes.

**Comment by slackner** [comment]
Okay, updated! Please let me know if you are fine with these changes. (If you already did some of them yourself, that is also fine ofc.)

**Comment by rfjakob** [comment]
Looks good, thanks!

**Comment by slackner** [comment]
No problem. By the way: What is the reason for the new errors in the tests? They are not introduced by these commits, but a lot of tests fail with:

```
fatal: No names found, cannot describe anything.
```

**Comment by rfjakob** [comment]
This is because travis only clones the last 100 commits, and when we are more than 100 after the last tag, this happens. Just pushed a fix by bumping to 300.

**Pull request merged**
