### PR TITLE
syscallcompat: Implement workaround for Fchmodat with AT_SYMLINK_NOFOLLOW.

### PR DESCRIPTION
**Pull request by slackner**
Fixes https://github.com/rfjakob/gocryptfs/issues/259

----

In this case we have to be a bit careful: Is the trick really supported on all versions of Linux?

### CODE REVIEW

**Comment by rfjakob** [comment]
Good question. Travis runs a really old kernel, so if Travis passes that's good enough I think.

Comment about the code: I don't see a reason why this should ever be called without NOFOLLOW, and the current code does not:

```
$ git grep syscallcompat.Fchmodat
internal/fusefrontend/fs.go:    err = syscallcompat.Fchmodat(dirfd, cName, mode, unix.AT_SYMLINK_NOFOLLOW)
internal/fusefrontend/fs_dir.go:                err = syscallcompat.Fchmodat(dirfd, cName, origMode, unix.AT_SYMLINK_NOFOLLOW)
internal/fusefrontend/fs_dir.go:                err = syscallcompat.Fchmodat(parentDirFd, cName, origMode|0700, unix.AT_SYMLINK_NOFOLLOW)
internal/fusefrontend/fs_dir.go:                                err = syscallcompat.Fchmodat(parentDirFd, cName, origMode, unix.AT_SYMLINK_NOFOLLOW)
```
I think we can drop the if, and maybe add a comment that NOFOLLOW is always used.

**Comment by rfjakob** [comment]
I'll check what glibc does, but it seems to also use the /proc/self/fd trick, https://manned.org/fchmodat.2#head8 :
```
NOTES
   C library/kernel differences
       The GNU C library fchmodat() wrapper function implements the POSIX-
       specified interface described in this page.  This interface differs
       from the underlying Linux system call, which does not have a flags
       argument.

   Glibc notes
       On older kernels where fchmodat() is unavailable, the glibc wrapper
       function falls back to the use of chmod().  When pathname is a relative
       pathname, glibc constructs a pathname based on the symbolic link in
       /proc/self/fd that corresponds to the dirfd argument.
```

**Comment by slackner** [comment]
I've dropped the support for `flags == 0` and added a comment similar to the other syscallcompat wrappers.

The glibc trick might be similar, but I haven't seen used this trick in combination with `O_PATH` yet. The manpage for `open` also explicitly writes that `fchmod` doesn't work, so I was a bit surprised to find that `chmod` on `/proc/self/fd/...` does.

```
       O_PATH (since Linux 2.6.39)
              Obtain a file descriptor that can be used for two purposes: to
              indicate a location in the filesystem tree and to perform
              operations that act purely at the file descriptor level.  The
              file itself is not opened, and other file operations (e.g.,
              read(2), write(2), fchmod(2), fchown(2), fgetxattr(2),
              ioctl(2), mmap(2)) fail with the error EBADF.
```

**Comment by rfjakob** [comment]
By the way, why don't we use

/proc/self/fd/$dirfd/$path

?

**Comment by slackner** [comment]
That would not work. Then `Chmod()` might resolve `path`, if it points to a symlink.

**Comment by rfjakob** [comment]
Lchmod()

**Comment by slackner** [comment]
But unfortunately that doesn't exist on Linux. You will only find BSD manpages.

**Comment by rfjakob** [comment]
Ah, I see.

**Comment by rfjakob** [comment]
I followed the fchmodat2 discussion at https://patchwork.kernel.org/patch/9596301/ , which ultimately led me to how qemu solves the problem: https://git.qemu.org/?p=qemu.git;a=blob;f=hw/9pfs/9p-local.c;h=08e673a79c2299d535e5cee4317af186ace80f6f;hb=HEAD#l371

I think we need an extra fstat before the chmod.

**Comment by slackner** [comment]
I've now added an explicit test for symlinks, which is definitely a bit safer. Based on my tests, however, it would have already worked before. `Chmod` returned an error (instead of following the symlink target) - at least, if I didn't make any other mistake during my tests.

**Comment by rfjakob** [comment]
I added a Fchmodat  symlink test 8253c55386e59295ea48dfc1b9beea4d785fcbbd . I found something pretty interesting: When you comment-out the `if a.IsSymlink()` check, the permissions on the symlink itself get changed!
```
/tmp/gocryptfs-test-parent/syscallcompat094547068$ ls -l | grep TestFchmodat_Symlink
l-wx-wx-wx. 1 jakob jakob   20 Jan  7 23:05 TestFchmodat_Symlink -> TestFchmodat_Regular
```
I don't think I have ever seen this.

**Comment by rfjakob** [comment]
Your change merged as https://github.com/rfjakob/gocryptfs/commit/4170ef00f32b3943a75f1c85c2b21dbe27ba30cd , thanks!

**Comment by slackner** [comment]
That sounds indeed a bit weird. Thanks for adding the tests!

BTW: When do you plan to release the next -rc? Two things that would be nice to get in before, if we still have sufficient time to address them:
* #327 ("Possible race-conditions between file creation and Fchownat")
* Verify, that we didn't break anything on macOS - did you already look into the Travis CI idea (mentioned in #307)

**Comment by rfjakob** [comment]
By the way, do you mean with

> Note that we can neither use Fchmodat (since fd is not necessarily a directory)

? Why would it help if fd is a directory?

**Comment by slackner** [comment]
For directories, we could also use `Fchmodat` with `path="."`, but not sure if that is necessarily better.

**Comment by rfjakob** [comment]
So I'm back at my day job this week, next rc on the weekend I guess. I absolutely want to fix #327 as it is a security issue.

**Pull request closed without merging**
