### PR TITLE
remove Trezor support

### PR DESCRIPTION
**Pull request by prusnak**
Let's remove remnants of non-functional Trezor support.

We'll implemented the Trezor support via FIDO2.

### CODE REVIEW

**Comment by rfjakob** [comment]
Good. I wanted to do this for some time now. Merged, thanks!

**Comment by tehcodedninja** [comment]
Is there a status update on FIDO2 implementation?

**Comment by prusnak** [comment]
> Is there a status update on FIDO2 implementation?

No, but it should be pretty trivial via a shell script. Gocryptfs allows you to call an external script to obtain the passphrase via `-extpass`. You can generate this passphrase via creating a HMAC FIDO2 credential using `fido2-cred -M -h`.

**Comment by prusnak** [comment]
@tehcodedninja I implemented FIDO2 in https://github.com/rfjakob/gocryptfs/pull/505 - comments are welcome in the PR

**Pull request merged**
